name: Docker Image CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Build the Docker image
      env:
        GITHUB_TOKEN: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}
      run: |
        docker build . \
          --file Dockerfile \
          --tag my-image-name:$(date +%s)
