name: Docker Image CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set Docker Permissions
      run: |
        sudo usermod -aG docker $USER
        newgrp docker
        sudo chmod 666 /var/run/docker.sock

    - name: Build the Docker image
      env:
        DOCKER_BUILDKIT: 1
      run: |
        docker build . \
          --file Dockerfile \
          --tag my-image-name:$(date +%s)
