name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Step 2: Build the Docker image
    - name: Build the Docker image
      run: |
        docker build . \
          --file Dockerfile \
          --tag my-image-name:$(date +%s)
