name: Node.js CI with Bun and PM2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.12.0]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Bun
      run: |
        curl -fsSL https://bun.sh/install | bash
        echo "$HOME/.bun/bin" >> $GITHUB_PATH
        bun --version

    - name: Install PM2 Globally
      run: |
        npm install -g pm2
        echo "$(npm bin -g)" >> $GITHUB_PATH
        pm2 --version

    - name: Install dependencies with Bun
      run: bun install

    - name: Build the source code
      run: |
        bun build index.ts --if-present

    - name: Run Tests
      run: |
        bun test

    - name: Start or Restart Application with PM2
      run: |
        pm2 restart index.ts --name "my-app" --watch || pm2 restart "my-app"
        pm2 save

    - name: Verify PM2 Process
      run: |
        pm2 list
