name: Node.js CI with OWASP Dependency Check, PM2, Docker, and Trivy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    # Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Install OWASP Dependency Check
    - name: Install OWASP Dependency Check
      run: |
        curl -sSL https://github.com/jeremylong/DependencyCheck/releases/download/v7.4.1/dependency-check-7.4.1-release.zip -o dependency-check.zip
        unzip dependency-check.zip -d dependency-check
        chmod +x dependency-check/dependency-check/bin/dependency-check.sh

    # Run OWASP Dependency Check
    - name: Run OWASP Dependency Check
      run: |
        dependency-check/dependency-check/bin/dependency-check.sh \
          --scan . \
          --format "ALL" \
          --out ./owasp-report \
          --failOnCVSS 5 \
          --disableAssembly \
          --suppression suppressions.xml || true
        if [ ! -d "./owasp-report" ]; then
          echo "OWASP report directory not found!"
          exit 1
        fi

    # Upload OWASP Reports
    - name: Upload OWASP Reports
      uses: actions/upload-artifact@v3
      with:
        name: OWASP Dependency Check Report
        path: ./owasp-report

    # Set up Node.js
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22.12.0

    # Check and Install Bun
    - name: Ensure Bun is Installed
      run: |
        if ! command -v bun &> /dev/null; then
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH
        fi
        bun --version

    # Check and Install PM2
    - name: Ensure PM2 is Installed
      run: |
        if ! command -v pm2 &> /dev/null; then
          npm install -g pm2
          echo "$(npm bin -g)" >> $GITHUB_PATH
        fi
        pm2 --version

    # Install dependencies with Bun
    - name: Install Dependencies
      run: bun install

    # Build the source code
    - name: Build the Source Code
      run: |
        bun build index.ts --if-present
