name: Node.js CI with Bun and PM2 Restart

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    permissions:
      actions: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Bun
      run: |
        curl -fsSL https://bun.sh/install | bash
        echo "PATH=$HOME/.bun/bin:\$PATH" >> $GITHUB_ENV
        export PATH=$HOME/.bun/bin:$PATH
        bun --version

   

    - name: Add npm Global Bin to PATH
      run: echo "PATH=$(npm bin -g):\$PATH" >> $GITHUB_ENV

    - name: Verify PM2 Installation
      run: pm2 --version

    - name: Install dependencies with Bun
      run: bun install

    - name: Build the source code
      run: bun build index.ts --if-present

    - name: Run Tests
      run: bun test

    - name: Restart Application with PM2
      run: pm2 restart index.ts
