name: Node.js CI with Bun and PM2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.12.0]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Bun
      run: |
        curl -fsSL https://bun.sh/install | bash
        echo "PATH=$HOME/.bun/bin:\$PATH" >> $GITHUB_ENV
        export PATH=$HOME/.bun/bin:$PATH
        bun --version

    - name: Install PM2
      run: npm install -g pm2

    - name: Add npm Global Bin to PATH
      run: echo "PATH=$(npm bin -g):\$PATH" >> $GITHUB_ENV

    - name: Verify PM2 Installation
      run: pm2 --version

    - name: Install dependencies with Bun
      run: bun install

    - name: Build the source code
      run: bun build index.ts --if-present

    - name: Run Tests
      run: bun test

    - name: Restart with PM2
      run: pm2 restart index.ts
