name: Node.js CI with Bun

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.12.0]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Bun
      run: |
        curl -fsSL https://bun.sh/install | bash
        echo "PATH=$HOME/.bun/bin:\$PATH" >> $GITHUB_ENV
        export PATH=$HOME/.bun/bin:$PATH
        bun --version

    - name: Install dependencies with Bun
      run: bun install

    - name: Build the source code
      run: bun build src/index.ts --if-present

    - name: Run Tests
      run: bun test
