name: Node.js CI with SonarQube

on:
  push:
    branches: [ "main" ]
  pull_request_target:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Debug SonarQube Secrets
      run: |
        echo "SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}"
        echo "SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}"
        echo "SONAR_TOKEN is set: [${{ secrets.SONAR_TOKEN != '' }}]"

    - name: Debug Environment Variables
      run: env

    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@v1
      with:
        projectBaseDir: .
        args: >
          -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
